# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: install golint
      run: go install golang.org/x/lint/golint@latest

    - name: lint
      run: make lint

    - name: lint
      run: make vuln

    - name: run unit test
      run: go test -v ./...
